### ISSUE TITLE
调用FloatWindow.destroy()后闪退

### ISSUE THREAD

**Issue by Leu-Z** [SDKers/FloatWindow#14]
已经初始化过了，每次调用FloatWindow.destroy()都会报错。
多次尝试后发现，如果之前调用过FloatWindow.show()，就不会再报错了。
请问这个问题怎么解决？

```  java.lang.RuntimeException: Unable to destroy activity {com.bestsch.classboard/com.bestsch.classboard.mvp.ui.activity.MainActivity}: java.lang.IllegalArgumentException: View=android.widget.FrameLayout{29cecb49 V.E..... ......ID 0,0-0,0} not attached to window manager
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3706)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
        at android.app.ActivityThread.access$1400(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: View=android.widget.FrameLayout{29cecb49 V.E..... ......ID 0,0-0,0} not attached to window manager
        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
        at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:111)
        at com.yhao.floatwindow.impl.FloatPhone.dismiss(FloatPhone.java:129)
        at com.yhao.floatwindow.impl.IFloatWindowImpl.dismiss(IFloatWindowImpl.java:136)
        at com.yhao.floatwindow.FloatWindow.destroy(FloatWindow.java:69)
        at com.yhao.floatwindow.FloatWindow.destroy(FloatWindow.java:57)
        at com.bestsch.classboard.mvp.ui.activity.MainActivity.onDestroy(MainActivity.java:388)
        at android.app.Activity.performDestroy(Activity.java:6169)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by Leu-Z** [comment]
看了一下源码，的确是show()之后，才调用的mWindowManager.addView(mView, mLayoutParams);
如果没有addView直接removeView就会报错了。

**Comment by hhhaiai** [comment]
最近在处理工作问题，这几天就开始修复
谢谢您的反馈

**Comment by hhhaiai** [comment]
> mWindowManager

如何调用情况下出的问题

**Comment by Leu-Z** [comment]
我没有理解您的问题的意思，现在的情况就是在初始化完成后，没有调用过FloatWindow.show()，而是直接调用了FloatWindow.destroy()，就会报错。
原因是WindowManager在调用FloatWindow.show()加入View之前之前是空的，没法再remove了。
